#version: '3.3'
#
#services:
#  app:
#    image: skypro_test
#  db:
#    image: postgres
#    environment:
#      - POSTGRES_USER=${DB_NAME}
#      - POSTGRES_PASSWORD=db_password
#      - POSTGRES_DB=db_name
#    ports:
#      - "5434:5432"
