version: '3.3'

services:
  app:
    image: stereo2025/skypro
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_NAME}
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_name
    ports:
      - 80:80
