version: '3.3'

services:
  app:
    image: stereo2025/skypro:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 80:80
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
  db:
    image: postgres
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME